apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: controlnet-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.20, pipelines.kubeflow.org/pipeline_compilation_time: '2023-05-09T16:45:20.550193',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline that collects
      data to train ControlNet", "inputs": [{"default": "{\"base_path\": \"soy-audio-379412-kfp-output\",
      \"run_id\": \"{{workflow.name}}\"}", "name": "metadata", "optional": true, "type":
      "String"}], "name": "controlnet-pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.20}
spec:
  entrypoint: controlnet-pipeline
  templates:
  - name: controlnet-pipeline
    inputs:
      parameters:
      - {name: metadata}
    dag:
      tasks:
      - name: generate-prompts
        template: generate-prompts
        arguments:
          parameters:
          - {name: metadata, value: '{{inputs.parameters.metadata}}'}
  - name: generate-prompts
    container:
      args: []
      command: [python3, main.py, --metadata, '{{inputs.parameters.metadata}}', --output_manifest_path,
        /tmp/outputs/output_manifest_path/data]
      image: ghcr.io/ml6team/generate_prompts:latest
    inputs:
      parameters:
      - {name: metadata}
    outputs:
      artifacts:
      - {name: generate-prompts-output_manifest_path, path: /tmp/outputs/output_manifest_path/data}
    metadata:
      annotations: {pipelines.kubeflow.org/task_display_name: Generate initial prompts,
        pipelines.kubeflow.org/component_spec: '{"description": "Component that generates
          a set of seed prompts.", "implementation": {"container": {"command": ["python3",
          "main.py", "--metadata", {"inputValue": "metadata"}, "--output_manifest_path",
          {"outputPath": "output_manifest_path"}], "image": "ghcr.io/ml6team/generate_prompts:latest"}},
          "inputs": [{"description": "Metadata arguments, passed as a json dict string",
          "name": "metadata", "type": "String"}], "name": "Generate prompts", "outputs":
          [{"description": "Path to the output manifest", "name": "output_manifest_path"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "7f376678aecdf3ab48bc06d5fd7457030ebf62a403ff7838224170bf32bd2bf8",
          "url": "components/generate_prompts/kubeflow_component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"metadata":
          "{{inputs.parameters.metadata}}"}'}
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.20
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters:
    - {name: metadata, value: '{"base_path": "soy-audio-379412-kfp-output", "run_id":
        "{{workflow.name}}"}'}
  serviceAccountName: pipeline-runner
