VALID_COMMONCRAWL_INDEX_FILTERS = [
    "url_surtkey",
    "url",
    "url_host_name",
    "url_host_tld",
    "url_host_2nd_last_part",
    "url_host_3rd_last_part",
    "url_host_4th_last_part",
    "url_host_5th_last_part",
    "url_host_registry_suffix",
    "url_host_registered_domain",
    "url_host_private_suffix",
    "url_host_private_domain",
    "url_host_name_reversed",
    "url_protocol",
    "url_port",
    "url_path",
    "url_query",
    "url_fragment",
    "fetch_time",
    "fetch_status",
    "fetch_redirect",
    "content_digest",
    "content_mime_type",
    "content_mime_detected",
    "content_charset",
    "content_languages",
    "content_truncated",
    "warc_filename",
    "warc_record_offset",
    "warc_record_length",
    "warc_segment",
    "crawl",
    "subset",
]

VALID_OPERATORS = [
    "==",
    "!=",
    "<",
    "<=",
    ">",
    ">=",
    "in",
    "not in",
    "like",
    "not like",
]

WARC_OUTPUT_COLUMNS = [
    "url_surtkey",
    "url",
    "warc_filename",
    "warc_record_offset",
    "warc_record_length",
]
