services:
  filter_comments:
    command:
    - --metadata
    - '{"run_id": "Stack filtering pipeline-20230621155412", "base_path": "gs://soy-audio-379412_kfp-artifacts/custom_artifact"}'
    - --output_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/filter_comments/manifest.json
    - --min_comments_ratio
    - '0.1'
    - --max_comments_ratio
    - '0.9'
    - --component_spec
    - '{"name": "Filter comments", "description": "Component that filters code based
      on the code to comment ratio", "image": "ghcr.io/ml6team/filter_comments:latest",
      "consumes": {"code": {"fields": {"content": {"type": "string"}}}}, "args": {"min_comments_ratio":
      {"description": "The minimum code to comment ratio", "type": "float"}, "max_comments_ratio":
      {"description": "The maximum code to comment ratio", "type": "float"}}}'
    - --input_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/filter_line_length/manifest.json
    depends_on:
      filter_line_length:
        condition: service_completed_successfully
    image: ghcr.io/ml6team/filter_comments:latest
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
  filter_line_length:
    command:
    - --metadata
    - '{"run_id": "Stack filtering pipeline-20230621155412", "base_path": "gs://soy-audio-379412_kfp-artifacts/custom_artifact"}'
    - --output_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/filter_line_length/manifest.json
    - --avg_line_length_threshold
    - '10'
    - --max_line_length_threshold
    - '100'
    - --alphanum_fraction_threshold
    - '0.25'
    - --component_spec
    - '{"name": "Filter line length", "description": "Component that filters code
      based on line length", "image": "ghcr.io/ml6team/filter_line_length:latest",
      "consumes": {"code": {"fields": {"avg_line_length": {"type": "float64"}, "max_line_length":
      {"type": "int32"}, "alphanum_fraction": {"type": "float64"}}}}, "args": {"avg_line_length_threshold":
      {"description": "Threshold for average line length to filter on", "type": "int"},
      "max_line_length_threshold": {"description": "Threshold for maximum line length
      to filter on", "type": "int"}, "alphanum_fraction_threshold": {"description":
      "Alphanum fraction to filter on", "type": "float"}}}'
    - --input_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/load_code_dataset_from_hub/manifest.json
    depends_on:
      load_code_dataset_from_hub:
        condition: service_completed_successfully
    image: ghcr.io/ml6team/filter_line_length:latest
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
  load_code_dataset_from_hub:
    command:
    - --metadata
    - '{"run_id": "Stack filtering pipeline-20230621155412", "base_path": "gs://soy-audio-379412_kfp-artifacts/custom_artifact"}'
    - --output_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/load_code_dataset_from_hub/manifest.json
    - --dataset_name
    - ml6team/the-stack-smol-python
    - --column_name_mapping
    - '{"content": "code_content", "lang": "code_lang", "size": "code_size", "path":
      "code_path", "repository_name": "code_repository_name", "avg_line_length": "code_avg_line_length",
      "max_line_length": "code_max_line_length", "alphanum_fraction": "code_alphanum_fraction"}'
    - --n_rows_to_load
    - None
    - --component_spec
    - '{"name": "Load code dataset from hub", "description": "Component that loads
      the stack dataset from the hub", "image": "ghcr.io/ml6team/load_from_hf_hub:latest",
      "produces": {"code": {"fields": {"content": {"type": "string"}, "lang": {"type":
      "string"}, "size": {"type": "int32"}, "path": {"type": "string"}, "repository_name":
      {"type": "string"}, "avg_line_length": {"type": "float64"}, "max_line_length":
      {"type": "int32"}, "alphanum_fraction": {"type": "float64"}}}}, "args": {"dataset_name":
      {"description": "Name of dataset on the hub", "type": "str"}, "column_name_mapping":
      {"description": "Mapping of the consumed hub dataset to fondant column names",
      "type": "dict"}, "image_column_names": {"description": "A list containing the
      original hub image column names. Used to format the image from HF hub format
      to a byte string", "type": "list", "default": "None"}, "n_rows_to_load": {"description":
      "Optional argument that defines the number of rows to load. Useful for testing
      pipeline runs on a small scale", "type": "int", "default": "None"}}}'
    depends_on: {}
    image: ghcr.io/ml6team/load_from_hf_hub:latest
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
  pii_redaction:
    command:
    - --metadata
    - '{"run_id": "Stack filtering pipeline-20230621155412", "base_path": "gs://soy-audio-379412_kfp-artifacts/custom_artifact"}'
    - --output_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/pii_redaction/manifest.json
    - --component_spec
    - '{"name": "PII redaction", "description": "A component that detects and redacts
      Personal Identifiable Information (PII) from code.", "image": "ghcr.io/ml6team/pii_redaction:latest",
      "consumes": {"code": {"fields": {"content": {"type": "string"}}}}, "produces":
      {"code": {"fields": {"content": {"type": "string"}}, "additionalFields": false},
      "additionalSubsets": false}}'
    - --input_manifest_path
    - gs://soy-audio-379412_kfp-artifacts/custom_artifact/filter_comments/manifest.json
    depends_on:
      filter_comments:
        condition: service_completed_successfully
    image: ghcr.io/ml6team/pii_redaction:latest
    volumes:
    - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
version: '3.8'
