authors:
  RobbeSneyders:
    name: Robbe Sneyders
    description: Tech Lead
    avatar: https://avatars.githubusercontent.com/u/20990866
  mrchtr:
    name: Matthias Richter
    description: ML Engineer
    avatar: https://avatars.githubusercontent.com/u/15777729
