services:
  load_code_dataset_from_hub:
    command:
      - --metadata
      - '{"run_id": "Stack filtering pipeline", "base_path": "/artifacts"}'
      - --output_manifest_path
      - /artifacts/manifest.txt
      - --dataset_name
      - ml6team/the-stack-smol-python
      - --component_spec
      - "{}"
    image: localhost:5003/ml6team/load_from_hub_stack:v2
    depends_on: {}
    volumes:
      - &id001
        source: /Users/bertchristiaens/Bitbucket/fondant_ml6/artifacts
        target: /artifacts
        type: bind
  data_explorer:
    image: localhost:5003/data_explorer:latest
    ports:
      - "8501:8501"
    volumes:
      - *id001

version: '3.8'
